language: csharp
mono:
  - beta
solution: Mod.Framework.sln
install:
  - mozroots --import --sync
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono nuget.exe restore Mod.Framework.sln
script:
  - msbuild Mod.Framework.sln /verbosity:minimal 
