name: Build

on:
  push:
    branches: [ default ]
  pull_request:
    branches: [ default ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: CI

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ModFramework.sln --configuration Release --no-restore
