name: Build

on:
  push:
    branches: [ default ]
  pull_request:
    branches: [ default ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: MonoMod dev build
      run: dotnet nuget add source https://pkgs.dev.azure.com/MonoMod/MonoMod/_packaging/DevBuilds%40Local/nuget/v3/index.json -n DevBuilds@Local
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ModFramework.sln --configuration Release --no-restore
