name: "CI-NuGet"

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PACKAGES_PATH: ${{ github.workspace }}/nuget-packages/

jobs:

  publish:
    runs-on: ubuntu-26.04
    environment: NuGet (Stable)
    permissions:
      id-token: write

    steps:
      - name: Get Run ID
        id: get-run-id
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          workflows_json="$(curl --fail-with-body -L \
              -H 'Accept: application/vnd.github+json' \
              -H 'X-GitHub-Api-Version: 2026-03-10' \
              'https://api.github.com/repos/'"$GITHUB_REPOSITORY"'/actions/workflows/ci.yml/runs?branch=upcoming&per_page=1'
          )"

          # heredocs do not have the NUL byte at the end, so read will always fail, but it will write to the variables anyway
          IFS=$'\n' read -d '' -r workflow_id workflow_conclusion <<<"$(jq -r '.workflow_runs[0].id, .workflow_runs[0].conclusion' <<<$workflows_json)" || true

          if [[ "$workflow_conclusion" != "success" ]]; then
            echo 'Last workflow run is not successful.'
            exit 1
          fi

          echo 'workflow-id='"$workflow_id" >> "$GITHUB_OUTPUT"

      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          name: Ubuntu PC NuGet Package
          run-id: ${{ steps.get-run-id.outputs.workflow-id }}
          path: ${{ env.PACKAGES_PATH }}
          merge-multiple: false
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: nuget-login
        with:
          user: DGSP

      - name: "Releasing to NuGet: ${{ matrix.profile.name }}"
        env:
          NUGET_API_KEY: ${{ steps.nuget-login.outputs.NUGET_API_KEY }}
        run: dotnet nuget push "$PACKAGES_PATH"*.nupkg --source https://api.nuget.org/v3/index.json --api-key "$NUGET_API_KEY"
