# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the upcoming branch
  push:
    branches: [ upcoming ]
  pull_request:
    branches: [ ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Server:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        profile: [
          {
            name: PC,
            patch_target: p,
            package_path: OTAPI.PC.nupkg,
            binaries_path: artifact-pc,
            wiki_md_file: OTAPI.PC.Server.mfw.md,
          },
          {
            name: Mobile,
            patch_target: m,
            package_path: OTAPI.Mobile.nupkg,
            binaries_path: artifact-mobile,
            wiki_md_file: OTAPI.Mobile.Server.mfw.md,
          },
          {
            name: tML,
            patch_target: t,
            package_path: OTAPI.TML.nupkg,
            binaries_path: artifact-tml,
            wiki_md_file: OTAPI.TML.PC.Server.mfw.md,
          },
        ]

    name: ${{ matrix.profile.name }} Server

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build the project
        run: |
          (cd OTAPI.Patcher && exec dotnet run -patchTarget=${{ matrix.profile.patch_target }} -latest=n --framework net6.0)
          (cd OTAPI.Server.Launcher && exec dotnet run -test-init)

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.profile.name }} NuGet Package
          path: OTAPI.Patcher/bin/Debug/net6.0/${{ matrix.profile.package_path }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.profile.name }} Binaries
          path: |
            OTAPI.Patcher/bin/Debug/net6.0/${{ matrix.profile.binaries_path }}/COPYING.txt
            OTAPI.Patcher/bin/Debug/net6.0/${{ matrix.profile.binaries_path }}/OTAPI.dll
            OTAPI.Patcher/bin/Debug/net6.0/${{ matrix.profile.binaries_path }}/OTAPI.Runtime.dll

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.profile.name }} Wiki MD files
          path: OTAPI.Patcher/bin/Debug/net6.0/${{ matrix.profile.wiki_md_file }}
